#ifndef HEADER_HPP
#define HEADER_HPP

#include <SFML/Graphics.hpp>
#include "GravitySource.hpp"
#include "Particle.hpp"
#include <vector>
#include <cstdlib>
#include <ctime>

#define SEED 5 // Seed for srand generation
#define FPS_LIMIT 60 // Frames per second limit
#define WINDOW_WIDTH 1600 // Width of the simulation window
#define WINDOW_HEIGHT 1000 // Height of the simulation window
#define STRENGTH 5000 // Strength of the gravity source
#define SOURCE_RADIUS 20 // Gravity source shape radius
#define PARTICLE_RADIUS 5 // Particle shape radius
#define MULTIPLE_PARTICLES_AMOUNT 10 // Amount of particles generated by a mouse click

class GravityProject {
public:
    GravityProject();
    void run();
private:
    void processEvents();
    void update();
    void check_collisions();
    void render();

    // Targeted window for drawing elements
    sf::RenderWindow mWindow;

    // Vector that is storing created GravitySource objects
    std::vector<GravitySource> mGravitySources;

    // Vector that is storing created Particle objects
    std::vector<Particle> mParticles;

    // Boolean for indicating whether the game is paused
    bool mPaused;
};

#endif